id: P000304
initial_creation_type: ocr
created_at: 11/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23871
  title: སྒྲུབ་པ་ཉམས་སུ་བླང་བའི་ལག་ལེན་དགོས་འདོད་འབྱུང་བའི་གཏེར་མཛོད
  author: ''
  volumes:
    435ba01f0743407da2c18795938ac43e:
      image_group_id: I3608
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
